services:
        web:
                image: flask_open
                build: .
                env_file:
                        - path: .env
                          required: false
                ports:
                        - "8321:8321"
                volumes:
                        - ./instance:/app/instance
                restart: unless-stopped

        socketio:
                image: socket_open
                build: ./socket
                ports:
                        - "8500:8500"
                restart: unless-stopped

        volunteer-api:
                image: fopl_volunteer_api
                build: ../fopl-volunteer-api
                ports:
                        - "8322:3000"
                volumes:
                        - ../fopl-volunteer-api/data:/app/data
                restart: unless-stopped